### ISSUE TITLE
reporte librerias

### ISSUE THREAD

**Issue by Edwin38H** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Edwin38H#2]
[REPORTE.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Edwin38H/files/6385394/REPORTE.pdf)

**Comment by carlos-chrs** [comment]
calificado 
100

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
